#!/bin/sh

echo $FLAG > /flag && export FLAG=not_flag && FLAG=not_flag

echo "Starting php fpm"
php-fpm &
echo "Starting nginx"
nginx &
echo "Starting mysql"
mysqld_safe&

echo "Server started."

tail -F /dev/null
